#ifndef OPENCV_3_0_COMPATIBILITY_HPP
#define OPENCV_3_0_COMPATIBILITY_HPP

#if CV_VERSION_MAJOR == 3
#include <opencv2/imgcodecs/imgcodecs.hpp>

#define CV_YCrCb2BGR cv::COLOR_YCrCb2BGR
#define CV_GRAY2BGR cv::COLOR_GRAY2BGR
#define CV_GRAY2RGB cv::COLOR_GRAY2RGB
#define CV_BGR2GRAY cv::COLOR_BGR2GRAY
#define CV_BGR2YCrCb cv::COLOR_BGR2YCrCb
#define CV_YCrCb2BGR cv::COLOR_YCrCb2BGR
#define CV_IMWRITE_JPEG_QUALITY cv::IMWRITE_JPEG_QUALITY
#define CV_LOAD_IMAGE_COLOR cv::IMREAD_COLOR
#define CV_AA cv::LINE_AA
#define CV_RANSAC cv::RANSAC
#endif //CV_VERSION_MAJOR == 3

#endif // OPENCV_3_0_COMPATIBILITY_HPP
